<?php
	return [
		"BOOTSTRAP" => "Bootstrap",
		"TAILWIND" => "Tailwind",
		"FOUNDATION" => "Foundation",
		"CUSTOM" => "自定义",
		"LABEL" => "标签",
		"DELETE" => "删除",
		"USE_CUSTOM_BASE_URL" => "使用自定义基础 URL",
		"CUSTOM_BASE_URL" => "自定义基础 URL",
		"USE_CUSTOM_BASE_URL_EXPLANATION" => "仅当您的仪表板使用与主网站不同的域名时，才设置自定义基础 URL。禁用后，录制将使用页面 URL 来确定基础 URL。",
		"CAPTURE_KEY_STROKES" => "捕获按键",
		"CAPTURE_KEY_STROKES_EXPLANATION" => "启用后，所有键盘交互都会被记录。这将允许您查看输入元素（如搜索框）中输入的文本。密码字段将自动忽略。",
		"IGNORE_KEY_STROKES" => "忽略按键",
		"IGNORE_KEY_STROKES_EXPLANATION" => "具有此类的元素将不会记录按键。",
		"RECORD_EXTERNAL_RESOURCES" => "记录外部脚本和图像",
		"RECORD_EXTERNAL_RESOURCES_EXPLANATION" => "默认情况下，只有外部内容的链接会被记录。如果外部内容更改或过期，则可能无法在回放时显示。启用此设置将确保脚本和图像在录制时被捕获，但录制将占用更多的存储空间。",
		"RECORDING_MOUSE_FREQUENCY" => "鼠标记录频率",
		"RECORDING_MOUSE_FREQUENCY_EXPLANATION" => "鼠标位置记录之间的时间间隔（毫秒）。较高的延迟将减少录制和数据传输的大小，但某些快速移动可能无法被准确捕获。鼠标点击将始终在正确的位置被捕获。",
		"RECORDING_TRIGGER_STRATEGY" => "录制触发策略",
		"RECORDING_TRIGGER_STRATEGY_EXPLANATION" => "选择会话页面如何分隔以及录制的每个部分如何开始。对于不使用传统页面导航的高级动态网站，您可能需要使用“自定义代码”选项。",
		"RECORDING_TRIGGER_OPTION_URL" => "页面 URL（仅路径）",
		"RECORDING_TRIGGER_OPTION_URL_EXPLANATION" => "每次页面路径更改或页面重新加载时，将开始新的录制。",
		"RECORDING_TRIGGER_OPTION_URL_QUERY" => "页面 URL（路径和查询）",
		"RECORDING_TRIGGER_OPTION_URL_QUERY_EXPLANATION" => "每次页面路径或查询参数更改，或页面重新加载时，将开始新的录制。",
		"RECORDING_TRIGGER_OPTION_CODE" => "自定义代码",
		"RECORDING_TRIGGER_OPTION_CODE_EXPLANATION" => "您将使用 JavaScript 定义何时开始录制以及如何对其进行分类。",
		"HEATMAP_RESOLUTION" => "热图分辨率",
		"HEATMAP_RESOLUTION_EXPLANATION" => "热图数据将根据分辨率汇总到各个时间段。较低的分辨率将允许您观察到该级别的数据（例如，1 小时将让您查看每小时的热图）。但较低的分辨率需要更多的数据库容量和资源。",
		"HEATMAP_MOUSE_PRECISION" => "热图鼠标精度",
		"HEATMAP_MOUSE_PRECISION_EXPLANATION" => "对于热图数据，像素级精度并非必要。降低精度可以减少数据库使用的资源。这不会影响录制。",
		"HEATMAP_DISPLAY_BREAKPOINTS" => "热图显示断点",
		"HEATMAP_DISPLAY_BREAKPOINTS_EXPLANATION" => "用户有许多不同的显示尺寸，响应式网站会调整其布局以支持这些尺寸。如果您使用流行的响应式框架，请从列表中选择它。否则，您可以自行设置。然后，您的热图数据将按显示尺寸组织。",
		"SHOW_BREAKPOINTS" => "显示断点",
		"STARTING_PIXELS_>=" => "起始像素 >="
	];