<?php
	return [
		"BOOTSTRAP" => "Bootstrap",
		"TAILWIND" => "Tailwind",
		"FOUNDATION" => "Foundation",
		"CUSTOM" => "Benutzerdefiniert",
		"LABEL" => "Beschriftung",
		"DELETE" => "Löschen",
		"USE_CUSTOM_BASE_URL" => "Benutzerdefinierte Basis-URL verwenden",
		"CUSTOM_BASE_URL" => "Benutzerdefinierte Basis-URL",
		"USE_CUSTOM_BASE_URL_EXPLANATION" => "Legen Sie nur dann eine benutzerdefinierte Basis-URL fest, wenn Ihr Dashboard einen anderen Domainnamen als die Hauptwebsite verwendet. Wenn diese Option deaktiviert ist, verwenden Aufzeichnungen die Seiten-URL, um die Basis-URL zu bestimmen.",
		"CAPTURE_KEY_STROKES" => "Tastenanschläge aufzeichnen",
		"CAPTURE_KEY_STROKES_EXPLANATION" => "Wenn aktiviert, werden alle Tastatureingaben aufgezeichnet. Dies ermöglicht es Ihnen, eingegebenen Text in Eingabeelementen wie Suchfeldern zu sehen. Passwortfelder werden automatisch ignoriert.",
		"IGNORE_KEY_STROKES" => "Tastenanschläge ignorieren",
		"IGNORE_KEY_STROKES_EXPLANATION" => "Elemente mit dieser Klasse werden keine Tastenanschläge aufzeichnen.",
		"RECORD_EXTERNAL_RESOURCES" => "Externe Skripte und Bilder aufzeichnen",
		"RECORD_EXTERNAL_RESOURCES_EXPLANATION" => "Standardmäßig werden nur die Links zu externen Inhalten aufgezeichnet. Wenn sich der externe Inhalt ändert oder abläuft, wird er möglicherweise bei Wiedergaben nicht angezeigt. Wenn Sie diese Einstellung aktivieren, wird sichergestellt, dass Skripte und Bilder zum Zeitpunkt der Aufzeichnung erfasst werden, aber die Aufzeichnungen benötigen mehr Speicherplatz.",
		"RECORDING_MOUSE_FREQUENCY" => "Aufzeichnungsfrequenz der Maus",
		"RECORDING_MOUSE_FREQUENCY_EXPLANATION" => "Die Zeit in Millisekunden zwischen den Aufzeichnungen der Mausposition. Eine höhere Verzögerung reduziert die Größe der Aufzeichnungen und den Datentransfer, aber einige schnelle Bewegungen werden möglicherweise nicht so genau erfasst. Mausklicks werden immer an der richtigen Position erfasst.",
		"RECORDING_TRIGGER_STRATEGY" => "Strategie zum Auslösen der Aufzeichnung",
		"RECORDING_TRIGGER_STRATEGY_EXPLANATION" => "Wählen Sie aus, wie Sitzungsseiten getrennt werden und wie jeder Teil der Aufzeichnung beginnt. Für fortgeschrittene und dynamische Websites, die keine traditionelle Seitennavigation verwenden, möchten Sie möglicherweise die Option \"Benutzerdefinierter Code\" nutzen.",
		"RECORDING_TRIGGER_OPTION_URL" => "Seiten-URL (nur Pfad)",
		"RECORDING_TRIGGER_OPTION_URL_QUERY" => "Seiten-URL (Pfad und Abfrage)",
		"RECORDING_TRIGGER_OPTION_CODE" => "Benutzerdefinierter Code",
		"HEATMAP_RESOLUTION" => "Heatmap-Auflösung",
		"HEATMAP_RESOLUTION_EXPLANATION" => "Heatmap-Daten werden basierend auf der Auflösung in Zeiträume zusammengefasst. Eine niedrigere Auflösung ermöglicht es Ihnen, Daten bis zu diesem Niveau zu beobachten (z. B. 1 Stunde zeigt Heatmaps stündlich an). Allerdings erfordern niedrigere Auflösungen mehr Datenbankkapazität und Ressourcen.",
		"HEATMAP_MOUSE_PRECISION" => "Mauspräzision der Heatmap",
		"HEATMAP_MOUSE_PRECISION_EXPLANATION" => "Pixelfeine Präzision ist für Heatmap-Daten nicht erforderlich. Eine Reduzierung der Präzision kann die von der Datenbank genutzten Ressourcen verringern. Dies beeinflusst die Aufzeichnungen nicht.",
		"HEATMAP_DISPLAY_BREAKPOINTS" => "Anzeige-Breakpoints der Heatmap",
		"HEATMAP_DISPLAY_BREAKPOINTS_EXPLANATION" => "Benutzer haben unterschiedliche Bildschirmgrößen, und responsive Websites passen ihr Layout entsprechend an. Wenn Sie ein bekanntes responsives Framework verwenden, wählen Sie es aus der Liste aus. Andernfalls können Sie eigene Einstellungen vornehmen. Ihre Heatmap-Daten werden dann nach Bildschirmgröße organisiert.",
		"SHOW_BREAKPOINTS" => "Breakpoints anzeigen",
		"STARTING_PIXELS_>=" => "Startpixel ≥",
	];