<?php
	return [
		"BOOTSTRAP" => "Bootstrap",
		"TAILWIND" => "Tailwind",
		"FOUNDATION" => "Foundation",
		"CUSTOM" => "Custom",
		"LABEL" => "Label",
		"DELETE" => "Delete",
		"SESSION_RECORDINGS" => "Session Recordings",
		"HEATMAPS" => "Heatmaps",
		"DATABASE" => "Database",
		"FILE_STORAGE" => "File Storage",
		"SETTINGS" => "Settings",
		"USE_CUSTOM_BASE_URL" => "Use custom base URL",
		"CUSTOM_BASE_URL" => "Custom Base URL",
		"USE_CUSTOM_BASE_URL_EXPLANATION" => "Set a custom base URL only if your dashboard uses a different domain name to the primary website. When disabled, recordings will use the page URL to determine the base URL.",
		"CAPTURE_KEY_STROKES" => "Capture key strokes",
		"CAPTURE_KEY_STROKES_EXPLANATION" => "When enabled, all keyboard interactions will be recorded. This will allow you to see text entered into input elements like search boxes. Password fields will be automatically ignored.",
		"IGNORE_KEY_STROKES" => "Ignore key strokes",
		"IGNORE_KEY_STROKES_EXPLANATION" => "Elements with this class will not have key strokes recorded.",
		"RECORD_EXTERNAL_RESOURCES" => "Record external scripts and images",
		"RECORD_EXTERNAL_RESOURCES_EXPLANATION" => "By default, only the links to external content will be recorded. If the external content changes or expires, then it may not show during replays. Enabling this setting will ensure that scripts and images are captured as they are at the time of the recording, but recordings will take up more storage space.",
		"RECORDING_MOUSE_FREQUENCY" => "Recording mouse frequency",
		"RECORDING_MOUSE_FREQUENCY_EXPLANATION" => "The time in milliseconds between mouse position recordings. A higher delay will reduce the size of recordings and data transfer, but some swift movements may not be captured as accurately. Mouse clicks will always be captured at the correct location.",
		"RECORDING_TRIGGER_STRATEGY" => "Recording trigger strategy",
		"RECORDING_TRIGGER_STRATEGY_EXPLANATION" => "Select how session pages will be separated and how each part of the recording will start. For advanced and dynamic websites that don't use traditional page navigation, you will likely want to make use of the \"Custom Code\" option.",
		"RECORDING_TRIGGER_OPTION_URL" => "Page URL (Path only)",
		"RECORDING_TRIGGER_OPTION_URL_EXPLANATION" => "A new recording will start each time the page path changes, or the page is reloaded.",
		"RECORDING_TRIGGER_OPTION_URL_QUERY" => "Page URL (Path and Query)",
		"RECORDING_TRIGGER_OPTION_URL_QUERY_EXPLANATION" => "A new recording will start each time the page path or query parameters change, or the page is reloaded.",
		"RECORDING_TRIGGER_OPTION_CODE" => "Custom Code",
		"RECORDING_TRIGGER_OPTION_CODE_EXPLANATION" => "You will define when recordings should start, and how they should be categorised using Javascript.",
		"HEATMAP_RESOLUTION" => "Heatmap resolution",
		"HEATMAP_RESOLUTION_EXPLANATION" => "Heatmap data will be collated into periods based on the resolution. A lower resolution will let you observe data down to that level (e.g. 1 hour will let you see heatmaps from hour to hour). But lower resolutions require more database capacity and resources.",
		"HEATMAP_MOUSE_PRECISION" => "Heatmap mouse precision",
		"HEATMAP_MOUSE_PRECISION_EXPLANATION" => "Pixel perfect precision is unneccesary for the heatmap data. Decreasing the precision can reduce the resources used by the database. This will not affect recordings.",
		"HEATMAP_DISPLAY_BREAKPOINTS" => "Heatmap display breakpoints",
		"HEATMAP_DISPLAY_BREAKPOINTS_EXPLANATION" => "Users have many different display sizes and responsive websites will adjust their layout to support them. If you use a popular responsive framework, select it from the list. Otherwise you can setup your own. Then your heatmap data will be organised by display size.",
		"SHOW_BREAKPOINTS" => "Show breakpoints",
		"STARTING_PIXELS_>=" => "Starting Pixels >="
	];