<?php
	return [
		"BOOTSTRAP" => "Bootstrap",
		"TAILWIND" => "Tailwind",
		"FOUNDATION" => "Foundation",
		"CUSTOM" => "Personalizado",
		"LABEL" => "Etiqueta",
		"DELETE" => "Eliminar",
		"SESSION_RECORDINGS" => "Grabaciones de sesión",
		"HEATMAPS" => "Mapas de calor",
		"DATABASE" => "Base de datos",
		"FILE_STORAGE" => "Almacenamiento de archivos",
		"SETTINGS" => "Configuraciones",
		"USE_CUSTOM_BASE_URL" => "Usar URL base personalizada",
		"CUSTOM_BASE_URL" => "URL base personalizada",
		"USE_CUSTOM_BASE_URL_EXPLANATION" => "Establezca una URL base personalizada solo si su panel utiliza un nombre de dominio diferente al del sitio web principal. Cuando está deshabilitado, las grabaciones usarán la URL de la página para determinar la URL base.",
		"CAPTURE_KEY_STROKES" => "Capturar pulsaciones de teclas",
		"CAPTURE_KEY_STROKES_EXPLANATION" => "Cuando está habilitado, todas las interacciones del teclado serán grabadas. Esto le permitirá ver el texto ingresado en elementos de entrada como cuadros de búsqueda. Los campos de contraseña serán ignorados automáticamente.",
		"IGNORE_KEY_STROKES" => "Ignorar pulsaciones de teclas",
		"IGNORE_KEY_STROKES_EXPLANATION" => "Los elementos con esta clase no tendrán registradas sus pulsaciones de teclas.",
		"RECORD_EXTERNAL_RESOURCES" => "Grabar scripts e imágenes externas",
		"RECORD_EXTERNAL_RESOURCES_EXPLANATION" => "De forma predeterminada, solo se grabarán los enlaces al contenido externo. Si el contenido externo cambia o expira, es posible que no se muestre durante las reproducciones. Al habilitar esta configuración, se asegurará de que los scripts e imágenes se capturen tal como están en el momento de la grabación, pero las grabaciones ocuparán más espacio de almacenamiento.",
		"RECORDING_MOUSE_FREQUENCY" => "Frecuencia de grabación del ratón",
		"RECORDING_MOUSE_FREQUENCY_EXPLANATION" => "El tiempo en milisegundos entre grabaciones de posición del ratón. Un retraso mayor reducirá el tamaño de las grabaciones y la transferencia de datos, pero algunos movimientos rápidos pueden no capturarse con tanta precisión. Los clics del ratón siempre se capturarán en la ubicación correcta.",
		"RECORDING_TRIGGER_STRATEGY" => "Estrategia de activación de grabación",
		"RECORDING_TRIGGER_STRATEGY_EXPLANATION" => "Seleccione cómo se separarán las páginas de sesión y cómo comenzará cada parte de la grabación. Para sitios web avanzados y dinámicos que no utilizan navegación de página tradicional, probablemente desee utilizar la opción \"Código personalizado\".",
		"RECORDING_TRIGGER_OPTION_URL" => "URL de la página (solo ruta)",
		"RECORDING_TRIGGER_OPTION_URL_EXPLANATION" => "Se iniciará una nueva grabación cada vez que cambie la ruta de la página o se recargue la página.",
		"RECORDING_TRIGGER_OPTION_URL_QUERY" => "URL de la página (ruta y consulta)",
		"RECORDING_TRIGGER_OPTION_URL_QUERY_EXPLANATION" => "Se iniciará una nueva grabación cada vez que cambie la ruta de la página o los parámetros de consulta, o se recargue la página.",
		"RECORDING_TRIGGER_OPTION_CODE" => "Código personalizado",
		"RECORDING_TRIGGER_OPTION_CODE_EXPLANATION" => "Definirá cuándo deben comenzar las grabaciones y cómo deben categorizarse utilizando JavaScript.",
		"HEATMAP_RESOLUTION" => "Resolución del mapa de calor",
		"HEATMAP_RESOLUTION_EXPLANATION" => "Los datos del mapa de calor se recopilarán en períodos basados en la resolución. Una resolución más baja le permitirá observar datos hasta ese nivel (por ejemplo, 1 hora le permitirá ver mapas de calor de hora en hora). Pero las resoluciones más bajas requieren más capacidad y recursos de base de datos.",
		"HEATMAP_MOUSE_PRECISION" => "Precisión del ratón en el mapa de calor",
		"HEATMAP_MOUSE_PRECISION_EXPLANATION" => "La precisión perfecta de píxeles no es necesaria para los datos del mapa de calor. Disminuir la precisión puede reducir los recursos utilizados por la base de datos. Esto no afectará las grabaciones.",
		"HEATMAP_DISPLAY_BREAKPOINTS" => "Puntos de interrupción de visualización del mapa de calor",
		"HEATMAP_DISPLAY_BREAKPOINTS_EXPLANATION" => "Los usuarios tienen muchos tamaños de pantalla diferentes y los sitios web responsivos ajustarán su diseño para soportarlos. Si utiliza un marco responsivo popular, selecciónelo de la lista. De lo contrario, puede configurar el suyo propio. Luego, sus datos de mapa de calor se organizarán por tamaño de pantalla.",
		"SHOW_BREAKPOINTS" => "Mostrar puntos de interrupción",
		"STARTING_PIXELS_>=" => "Píxeles iniciales >="
	];	