<?php
	return [
		"BOOTSTRAP" => "Bootstrap",
		"TAILWIND" => "Tailwind",
		"FOUNDATION" => "Foundation",
		"CUSTOM" => "カスタム",
		"LABEL" => "ラベル",
		"DELETE" => "削除",
		"USE_CUSTOM_BASE_URL" => "カスタムベースURLを使用する",
		"CUSTOM_BASE_URL" => "カスタムベースURL",
		"USE_CUSTOM_BASE_URL_EXPLANATION" => "ダッシュボードがメインサイトとは異なるドメイン名を使用している場合にのみ、カスタムベースURLを設定します。無効にすると、記録はページURLを使用してベースURLを決定します。",
		"CAPTURE_KEY_STROKES" => "キーストロークをキャプチャする",
		"CAPTURE_KEY_STROKES_EXPLANATION" => "有効にすると、すべてのキーボード操作が記録されます。これにより、検索ボックスなどの入力要素に入力されたテキストを確認できます。パスワードフィールドは自動的に無視されます。",
		"IGNORE_KEY_STROKES" => "キーストロークを無視する",
		"IGNORE_KEY_STROKES_EXPLANATION" => "このクラスを持つ要素は、キーストロークが記録されません。",
		"RECORD_EXTERNAL_RESOURCES" => "外部スクリプトと画像を記録する",
		"RECORD_EXTERNAL_RESOURCES_EXPLANATION" => "デフォルトでは、外部コンテンツへのリンクのみが記録されます。外部コンテンツが変更または期限切れになると、再生時に表示されない可能性があります。この設定を有効にすると、スクリプトや画像が記録時の状態でキャプチャされますが、記録はより多くのストレージスペースを使用します。",
		"RECORDING_MOUSE_FREQUENCY" => "マウス記録頻度",
		"RECORDING_MOUSE_FREQUENCY_EXPLANATION" => "マウス位置の記録間隔（ミリ秒）。遅延を長くすると、記録とデータ転送のサイズが減少しますが、一部の素早い動きは正確にキャプチャされない場合があります。マウスクリックは常に正しい位置でキャプチャされます。",
		"RECORDING_TRIGGER_STRATEGY" => "記録トリガー戦略",
		"RECORDING_TRIGGER_STRATEGY_EXPLANATION" => "セッションページをどのように分割し、記録の各部分をどのように開始するかを選択します。従来のページナビゲーションを使用しない高度で動的なウェブサイトの場合、「カスタムコード」オプションを利用することをお勧めします。",
		"RECORDING_TRIGGER_OPTION_URL" => "ページURL（パスのみ）",
		"RECORDING_TRIGGER_OPTION_URL_EXPLANATION" => "ページパスが変更されるか、ページがリロードされるたびに新しい記録が開始されます。",
		"RECORDING_TRIGGER_OPTION_URL_QUERY" => "ページURL（パスとクエリ）",
		"RECORDING_TRIGGER_OPTION_URL_QUERY_EXPLANATION" => "ページパスまたはクエリパラメータが変更されるか、ページがリロードされるたびに新しい記録が開始されます。",
		"RECORDING_TRIGGER_OPTION_CODE" => "カスタムコード",
		"RECORDING_TRIGGER_OPTION_CODE_EXPLANATION" => "記録をいつ開始し、JavaScriptを使用してどのように分類するかを定義します。",
		"HEATMAP_RESOLUTION" => "ヒートマップ解像度",
		"HEATMAP_RESOLUTION_EXPLANATION" => "ヒートマップデータは解像度に基づいて期間ごとに集計されます。解像度を低くすると、そのレベルまでデータを観察できます（例：1時間にすると、時間ごとのヒートマップを確認できます）。しかし、低解像度はより多くのデータベース容量とリソースを必要とします。",
		"HEATMAP_MOUSE_PRECISION" => "ヒートマップのマウス精度",
		"HEATMAP_MOUSE_PRECISION_EXPLANATION" => "ヒートマップデータにはピクセル単位の精度は不要です。精度を下げると、データベースが使用するリソースを削減できます。これは記録には影響しません。",
		"HEATMAP_DISPLAY_BREAKPOINTS" => "ヒートマップ表示ブレークポイント",
		"HEATMAP_DISPLAY_BREAKPOINTS_EXPLANATION" => "ユーザーはさまざまな表示サイズを持ち、レスポンシブなウェブサイトはそれらをサポートするためにレイアウトを調整します。人気のあるレスポンシブフレームワークを使用している場合は、リストから選択してください。そうでない場合は、自分で設定できます。その後、ヒートマップデータは表示サイズ別に整理されます。",
		"SHOW_BREAKPOINTS" => "ブレークポイントを表示",
		"STARTING_PIXELS_>=" => "開始ピクセル >="
	];